#! /usr/bin/env node

var markov = require('markov');
var fs = require('graceful-fs');

var util = require('./src/util')

var file = process.argv[2], start = process.argv[3];
if (!start) {
  start = file;
  file = util.getPath(new Date());
}

var seed = fs.readFileSync(file);
var m = markov();

m.seed(seed, function() {
  var response = m.respond("what is the meaning of life?", 25).join(' ');
  var firstPeriod = response.lastIndexOf('.');
  response = response.slice(0, firstPeriod + 1);
  console.log(response);
});
