#! /usr/bin/env node

var fs = require('graceful-fs');

var commander = require('commander');

var util = require('./src/util');

var processDate = function(date) {
  return util.importDate(date);
};
var today = new Date();

commander
  .option('-b, --begin <string>', 'Start of date range, inclusive (Jan 1)',
    processDate, new Date(today.getFullYear(), 0, 1))
  .option('-e, --end <string>',
    'End of date range, inclusive (today)', processDate, new Date())
  .option('-y, --year',
    'Make end date automatically the end of the year', false)
  .parse(process.argv);

const options = commander.opts();

var goBack = function(begin, end, year) {
  if (year) {
    end = new Date(today.getFullYear(), 11, 31)
  }

  var day = end, total = 0, journals = 0;

  console.log('begin: ' + renderDate(begin));
  console.log('end: ' + renderDate(end));

  while (day.getTime() >= begin.getTime()) {
    total++;

    if (checkDay(day)) {
      journals++;
    }

    day = util.incrementDay(day, -1);
  }

  var percent = (journals / total * 100).toFixed(2);
  console.log(
    percent + '%',
    '(' + journals + ' of ' + total + ' days)'
  );
};

var checkDay = function(date) {
  var file = util.getPath(date);

  return fs.existsSync(file);
};

var renderDate = function(date) {
  return util.shortDate(date) + ' (' + util.dayOfWeek(date) + ')';
};

goBack(options.begin, options.end, options.year);
