#! /usr/bin/env node

// TODO:
//   option to check how many days it's been a streak of no journals... -n option?

var fs = require('graceful-fs');
var commander = require('commander');

var util = require('./src/util');

commander
  .option('-d, --date <date>', 'Date to start with (today)',
    function(date) { return new Date(date); }, new Date())
  .parse(process.argv);

var goBack = function(start, check) {
  var day = start;
  var count = 0;

  while(checkDay(day)) {
    ++count;
    day = util.incrementDay(day, -1);
  }

  console.log(count + ' days in a row!');
};

var checkDay = function(date) {
  var file = util.getPath(date);

  if (fs.existsSync(file)) {
    return true;
  }

  return false;
};

goBack(commander.date, checkDay);
