#! /usr/bin/env node

// TODO:
//   option to check how many days it's been a streak of no journals... -n option?

var fs = require('graceful-fs');
var commander = require('commander');

var util = require('./src/util');
var processDate = function(date) {
  return util.importDate(date);
};

commander
  .option('-d, --date <date>', 'Date to start with (today)', processDate, util.normalizeDate(new Date()))
  .option('-v, --verbose', 'Show details of processing', false)
  .option('-y, --yesterday', 'Start date yesterdauy', false)
  .parse(process.argv);

const options = commander.opts();

var goBack = function(start, check) {
  var day = start;
  var count = 0;

  while(checkDay(day)) {
    ++count;
    if (options.verbose) {
      console.log(day);
    }
    day = util.incrementDay(day, -1);
  }

  console.log(count + ' days in a row!');
};

var checkDay = function(date) {
  var file = util.getPath(date);

  if (fs.existsSync(file)) {
    return true;
  }

  return false;
};

var date = options.yesterday ? util.incrementDay(util.normalizeDate(new Date()), -1) : options.date;

goBack(date, checkDay);
