#! /usr/bin/env node

var path = require('path');
var exec = require('child_process').exec;
var fs = require('graceful-fs');

var _ = require('lodash');
var commander = require('commander');

var util = require('./src/util');

commander
  .option('-d, --date <date>', 'Date to check (today, starting last year)',
    util.importDate, util.defaultDate())
  .option('-e, --editor', 'Open editor with the found files (don\'t open editor)')
  .option('-b, --back <n>', 'How many days to look back from the initial date (0)',
    parseInt, 0)
  .option('-f, --forward <n>', 'How many days to look forward from the initial date (0)',
    parseInt, 0)
  .option('-j, --journal', 'Look for daily journals (don\'t look for daily journals)')
  .option('-x, --extras', 'Look for extras - log and week files (don\'t look for extras)')
  .option('-m, --month', 'Look for monthly reviews (don\'t look for monthly reviews)')
  .option('-y, --year', 'Look for yearly review (don\'t look for yearly reviews)')
  .parse(process.argv);

const options = commander.opts();

var renderDate = function(date) {
  return util.shortDate(date) + ' (' + util.dayOfWeek(date) + ')';
};

var checkYear = function(today, year) {
  var day, thisYear = util.setYear(today, year);

  if (options.year) {
    var review = util.getYearReview(thisYear);
    if (fs.existsSync(review)) {
      files.push(review);
    }
  }

  if (checkDay(thisYear, 0)) {
    return;
  }

  if (options.back > 0) {
    for (var d = 1; d <= options.back; d++) {
      day = util.incrementDay(thisYear, -1 * d);

      if (checkDay(day, d, 'back')) {
        return;
      }
    }
  }

  if (options.forward > 0) {
    for (var d = 1; d <= options.forward; d++) {
      day = util.incrementDay(thisYear, 1 * d);

      if (checkDay(day, d, 'forward')) {
        return;
      }
    }
  }
};

var checkDay = function(date, count, label) {
  var file = util.getPath(date);
  var message = renderDate(date);
  var result = false;

  if (count !== 0) {
    message += ' (' + count + ' days ' + label + ')';
  }

  if (options.month) {
    var extra = util.getMonthPath(date);
    if (fs.existsSync(extra)) {
      message += ' [month]';
      files.push(extra);
      result = true;
    }
  }

  if (options.extras) {
    extra = util.getWeekPath(date);
    if (fs.existsSync(extra)) {
      message += ' [week]';
      files.push(extra);
      result = true;
    }

    extra = util.getLogPath(date);
    if (fs.existsSync(extra)) {
      message += ' [log]';
      files.push(extra);
      result = true;
    }

  }

  if (options.journal) {
    if (fs.existsSync(file)) {
      files.push(file);
      result = true;
    }
    else {
      message += ' [no journal]';
    }
  }

  if (result) {
    console.log(message);
  }

  return result;
};

var date = options.date;
var files = [];

for (var year = date.getFullYear(); year >= 1997; year--) {
  checkYear(date, year);
}

if (options.editor) {
  exec(`${process.env.EDITOR} .`);
  setTimeout(function() {
    exec(`${process.env.EDITOR} ${files.join(' ')}`);
  }, 500);
}
